class MenuData {
  final int itemID;
  final int itemCalories;
  final String itemName;
  String itemImage;
  final String itemDescription;
  final double itemPrice;

  MenuData({
    required this.itemID,
    required this.itemCalories,
    required this.itemName,
    required this.itemImage,
    required this.itemDescription,
    required this.itemPrice,
  });
}
class MenuRepository{

static List<MenuData> drinks = [
  MenuData(
      itemID: 1,
      itemName: "Espresso",
      itemImage: "assets/img/espresso.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.5,
      itemCalories: 0),
  MenuData(
      itemID: 2,
      itemName: "Americano",
      itemImage: "assets/img/americano.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.65,
      itemCalories: 0),
  MenuData(
      itemID: 3,
      itemName: "Cortado",
      itemImage: "assets/img/cortado.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 35),
  MenuData(
      itemID: 4,
      itemName: "Flat White",
      itemImage: "assets/img/flat_white.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 80),
  MenuData(
      itemID: 5,
      itemName: "Cappuccino",
      itemImage: "assets/img/cappuccino.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 100),
  MenuData(
      itemID: 6,
      itemName: "Latte",
      itemImage: "assets/img/latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 100),
  MenuData(
      itemID: 7,
      itemName: "Spanish Latte",
      itemImage: "assets/img/spanish_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 8,
      itemName: "White Mocha",
      itemImage: "assets/img/white_mocha.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 360),
  MenuData(
      itemID: 9,
      itemName: "Rose Latte",
      itemImage: "assets/img/rose_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 200),
  MenuData(
      itemID: 10,
      itemName: "Dolce de Leche Latte",
      itemImage: "assets/img/dolce_de_leche_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 11,
      itemName: "Matcha Latte",
      itemImage: "assets/img/matcha_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 110),
  MenuData(
      itemID: 12,
      itemName: "Turmeric Latte",
      itemImage: "",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 110),
  MenuData(
      itemID: 13,
      itemName: "V60",
      itemImage: "assets/img/v60.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 14,
      itemName: "Oz Hot Chocolate",
      itemImage: "assets/img/oz_hot_chocolate.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 230),
  MenuData(
      itemID: 15,
      itemName: "Icaed Americano",
      itemImage: "assets/img/iced_americano.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.65,
      itemCalories: 0),
  MenuData(
      itemID: 16,
      itemName: "Iced Latte",
      itemImage: "assets/img/iced_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 100),
  MenuData(
      itemID: 17,
      itemName: "Iced Spanish Latte",
      itemImage: "assets/img/iced_spanish_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 18,
      itemName: "Iced White Mocha",
      itemImage: "assets/img/iced_white_mocha.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 360),
  MenuData(
      itemID: 19,
      itemName: "Iced Rose Latte",
      itemImage: "assets/img/iced_rose_latte.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 200),
  MenuData(
      itemID: 20,
      itemName: "Iced Dolce de Leche Latte",
      itemImage: "",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 21,
      itemName: "Iced Matcha Latte",
      itemImage: "",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 110),
  MenuData(
      itemID: 22,
      itemName: "Oz Iced Shaken",
      itemImage: "assets/img/oz_iced_shaken.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.4,
      itemCalories: 390),
  MenuData(
      itemID: 23,
      itemName: "Iced Shaken Sugar free Caramel",
      itemImage: "assets/img/iced_shaken_sugar_free_caramel.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.4,
      itemCalories: 130),
  MenuData(
      itemID: 24,
      itemName: "Iced V60",
      itemImage: "assets/img/iced_v60.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 25,
      itemName: "Cold Brew",
      itemImage: "assets/img/cold_brew.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.7,
      itemCalories: 0),
  MenuData(
      itemID: 26,
      itemName: "Classic Mojito Sugar free",
      itemImage: "assets/img/classic_mojito_sugarfree.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 27,
      itemName: "Pinacolada Mojito Sugar free",
      itemImage: "assets/img/pinacolada_mojito_sugarfree.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 28,
      itemName: "Strawberry Mojito",
      itemImage: "assets/img/strawberry_mojito.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 29,
      itemName: "Detox Water",
      itemImage: "",
      itemDescription: "itemDescription",
      itemPrice: .5,
      itemCalories: 0),
  MenuData(
      itemID: 30,
      itemName: "Fresh Juices",
      itemImage: "assets/img/fresh_juices.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.0,
      itemCalories: 90),
  MenuData(
      itemID: 31,
      itemName: "Oz Signature Frappe",
      itemImage: "assets/img/oz_signature_frappe.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 440),
  MenuData(
      itemID: 31,
      itemName: "Caramel Mocha Frappe",
      itemImage: "assets/img/caramel_mocha_frappe.jpg",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 520),
  MenuData(
      itemID: 32,
      itemName: "Spanish Rose Frappe",
      itemImage: "",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 240),
  MenuData(
      itemID: 33,
      itemName: "Strawberry Matcha",
      itemImage: "",
      itemDescription: "Strawberry Sauce, Matcha powder, Milk",
      itemPrice: 2.5,
      itemCalories: 150),
];

static List<MenuData> meals = [
  MenuData(
      itemID: 34,
      itemName: "Philly Steak Sandwich",
      itemImage: "",
      itemDescription:
      "Beef ,multi seeds brown bread , green pepper , mushroom , white onion , cheese",
      itemPrice: 2.8,
      itemCalories: 470),
  MenuData(
      itemID: 35,
      itemName: "Halloumi Zaatar Sandwich",
      itemImage: "",
      itemDescription:
      "Grilled Halloumi , zaatar panini bread , Tomato , Cucumber",
      itemPrice: 2.5,
      itemCalories: 470),
  MenuData(
      itemID: 36,
      itemName: "Brisket Sliders",
      itemImage: "assets/img/brisket_sliders.jpg",
      itemDescription:
      "Beef brisket, potato bun slider, cheese, coleslaw, lettuce",
      itemPrice: 2.9,
      itemCalories: 440),
  MenuData(
      itemID: 37,
      itemName: "Shredded Chicken Sliders",
      itemImage: "assets/img/shredded_chicken_sliders.jpg",
      itemDescription:
      "Shredded Chicken, potato bun, cheese, coleslaw, lettuce",
      itemPrice: 2.4,
      itemCalories: 390),
  MenuData(
      itemID: 38,
      itemName: "Turkey Omelet Rye Sandwich",
      itemImage: "assets/img/turkey_omelet_rye_sandwich.jpg",
      itemDescription:
      "Turkey, Egg, Spanish, Rye toast, cheddar cheese, lettuce.",
      itemPrice: 2.3,
      itemCalories: 430),
  MenuData(
      itemID: 39,
      itemName: "Turkey Cheese Sandwich Slices",
      itemImage: "assets/img/turkey_cheese_sandwich_slices.jpg",
      itemDescription: "",
      itemPrice: 2.3,
      itemCalories: 410),
  MenuData(
      itemID: 40,
      itemName: "Egg and Turkey Croissant",
      itemImage: "assets/img/egg_and_turkey_croissant.jpg",
      itemDescription: "Egg, Turkey, croissant, cheddar cheese, sause",
      itemPrice: 2.5,
      itemCalories: 500),
  MenuData(
      itemID: 41,
      itemName: "Smoked turkey Croissant",
      itemImage: "assets/img/smoked_turkey_croissant.jpg",
      itemDescription: "",
      itemPrice: 2.3,
      itemCalories: 0),
  MenuData(
      itemID: 42,
      itemName: "Labneh Zaatar Croissant",
      itemImage: "",
      itemDescription: "assets/img/lebna_zaatar_croissant.jpg",
      itemPrice: 1.9,
      itemCalories: 410),
  MenuData(
      itemID: 43,
      itemName: "Halloumi Croissant",
      itemImage: "assets/img/halloumi_croissant.jpg",
      itemDescription: "Grill Halloumi, croissant, pesto sause",
      itemPrice: 2.4,
      itemCalories: 500),
  MenuData(
      itemID: 44,
      itemName: "Grilled Chicken Sandwich",
      itemImage: "",
      itemDescription:
      "Grilled chicken breast, Eggplants, Cheese, Brown Panini Bread",
      itemPrice: 2.5,
      itemCalories: 460),
  MenuData(
      itemID: 45,
      itemName: "Chicken Teriyaki",
      itemImage: "assets/img/chicken_teriyaki.jpg",
      itemDescription:
      "Grill Chicken, white rice, capsicum red, capsicum green, Spring onion, Sesame seed, Sause",
      itemPrice: 2.9,
      itemCalories: 430),
  MenuData(
      itemID: 46,
      itemName: "chicken Biryani",
      itemImage: "assets/img/chicken_biryani.jpg",
      itemDescription: "",
      itemPrice: 2.7,
      itemCalories: 440),
  MenuData(
      itemID: 47,
      itemName: "Chicken teriyaki linguine noodles",
      itemImage: "assets/img/chicken_teriyaki_noodles.jpg",
      itemDescription: "",
      itemPrice: 2.7,
      itemCalories: 380),
  MenuData(
      itemID: 48,
      itemName: "Chicken salad",
      itemImage: "assets/img/chicken_salad.jpg",
      itemDescription: "Mixed greens, Chicken, Balsamic Mustard Dressing",
      itemPrice: 2.3,
      itemCalories: 0),
  MenuData(
      itemID: 49,
      itemName: "Alfredo Pasta",
      itemImage: "",
      itemDescription: "Chicken, Pasta, Mushroom, Creamy Sauce",
      itemPrice: 2.8,
      itemCalories: 530),
  MenuData(
      itemID: 50,
      itemName: "Chicken Stroganoff",
      itemImage: "",
      itemDescription: "Rice, Creamy Sauce Chicken",
      itemPrice: 2.9,
      itemCalories: 550),
  MenuData(
      itemID: 51,
      itemName: "Thai Coconut Curry",
      itemImage: "",
      itemDescription: "Rice, Beef, Coconut Curry, Vegetables",
      itemPrice: 3.4,
      itemCalories: 440),
  MenuData(
      itemID: 52,
      itemName: "Cheese Sandwich",
      itemImage: "",
      itemDescription: "Three cheese, with Sun dried Tomato",
      itemPrice: 1.9,
      itemCalories: 320),
  MenuData(
      itemID: 53,
      itemName: "Egg and Cheese Sandwich",
      itemImage: "",
      itemDescription: "",
      itemPrice: 2.0,
      itemCalories: 0),
];

static List<MenuData> desserts = [

  MenuData(
      itemID: 54,
      itemName: "Peanuts Cocnuts Healthy Balls",
      itemImage: "assets/img/peanuts_cocnuts_healthy_balls.jpg",
      itemDescription: "",
      itemPrice: 1.5,
      itemCalories: 210),
  MenuData(
      itemID: 55,
      itemName: "Açaí bowl",
      itemImage: "assets/img/açaí_bowl.jpg",
      itemDescription: "",
      itemPrice: 3.9,
      itemCalories: 0),
  MenuData(
      itemID: 56,
      itemName: "French toast",
      itemImage: "assets/img/french_toast.jpg",
      itemDescription: "",
      itemPrice: 2.8,
      itemCalories: 0),
  MenuData(
      itemID: 57,
      itemName: "Pecan pie",
      itemImage: "assets/img/pecan_pie.jpg",
      itemDescription: "",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 58,
      itemName: "Chocolate cookies",
      itemImage: "assets/img/chocolate_cookies.jpg",
      itemDescription: "",
      itemPrice: 1.4,
      itemCalories: 0),
  MenuData(
      itemID: 59,
      itemName: "Lemon cake",
      itemImage: "assets/img/lemon_cake.jpg",
      itemDescription: "",
      itemPrice: 1.25,
      itemCalories: 0),
  MenuData(
      itemID: 60,
      itemName: "Nutella pancake",
      itemImage: "assets/img/nutella_pancake.jpg",
      itemDescription: "",
      itemPrice: 3.1,
      itemCalories: 0),
  MenuData(
      itemID: 61,
      itemName: "Granula Greek Yughort",
      itemImage: "",
      itemDescription: "",
      itemPrice: 1.8,
      itemCalories: 0),
];

static List<MenuData> breakfast = [

  MenuData(
      itemID: 62,
      itemName: "Oz classic Avocado Toast",
      itemImage: "assets/img/oz_classic_avocado_toast.jpg",
      itemDescription:
      "Toasted Sourdough bread, Guacamole, Poach Eggs , feta cheese, Fresh Pomegranate seeds and Garnish with chili flakes, sesame seeds . Parsley and Sakura mix.",
      itemPrice: 3.1,
      itemCalories: 400),
  MenuData(
      itemID: 63,
      itemName: "Grilled Mushrooms & Spinach Toast",
      itemImage: "assets/img/grilled_mushrooms__spinach_toast.jpg",
      itemDescription:
      "Toasted Sourdough bread, hummus, sauté spinach , Grilled Mushrooms and cherry Tomato , Garnish with chili flakes, sesame seeds, parsley and Sakura mix",
      itemPrice: 3.3,
      itemCalories: 368),
  MenuData(
      itemID: 64,
      itemName: "Labneh Zattar Toast",
      itemImage: "assets/img/labneh_zattar_toast.jpg",
      itemDescription:
      "Toasted sourdough bread, Labneh zattar mixture, Garnish with Sakura mix",
      itemPrice: 2.4,
      itemCalories: 331),
  MenuData(
      itemID: 65,
      itemName: "Guacamole Halloumi Toast",
      itemImage: "assets/img/guacamole_halloumi_toast.jpg",
      itemDescription:
      "Toasted sourdough bread , Sun-dried tomato sliced, grilled halloumi, Garnish with chili flakes , sesame seeds , parsley and Sakura mix .",
      itemPrice: 3.7,
      itemCalories: 501),
  MenuData(
      itemID: 66,
      itemName: "Truffle Mushroom & Egg Toast",
      itemImage: "assets/img/truffle_mushroom__egg_toast.jpg",
      itemDescription: "",
      itemPrice: 3.7,
      itemCalories: 434),
  MenuData(
      itemID: 67,
      itemName: "Olive Tapenade Halloumi Toast",
      itemImage: "assets/img/olive_tapenade_halloumi_toast.jpg",
      itemDescription: "",
      itemPrice: 3.4,
      itemCalories: 534),
  MenuData(
      itemID: 68,
      itemName: "Beetroot Hummus & Avocado Toast with Poached Egg",
      itemImage: "assets/img/beetroot_hummus__avocado_toast_with_egg.jpg",
      itemDescription:
      "Toasted sourdough bread , Beetroot hummus , sliced avocado , poached egg , almond flakes , Garnish with chili flakes , sesame seeds, parsley and Sakura mix",
      itemPrice: 3.7,
      itemCalories: 579),
  MenuData(
      itemID: 69,
      itemName: "Classic Egg Benedict",
      itemImage: "assets/img/classic_egg_benedict.jpg",
      itemDescription:
      "English Muffins buildup with spinach , poached egg, hollandaise sauce garnish with dill and Sakura mix served with wild rocket salad and cherry tomato .",
      itemPrice: 2.8,
      itemCalories: 446),
  MenuData(
      itemID: 70,
      itemName: "Scrambled Egg & Truffle Mushroom Sandwich",
      itemImage: "assets/img/scrambled_egg__truffle_mushroom_sandwich.jpg",
      itemDescription:
      "Brioche bun stuffed with Italian tomato sauce ,,scrambled egg, truffle mushroom, cheddar cheese . Garnish with parsley serve with wild rocket salad cans cherry tomato",
      itemPrice: 2.9,
      itemCalories: 543),
  MenuData(
      itemID: 71,
      itemName: "Oz Berry Pancake",
      itemImage: "assets/img/oz_berry_pancake.jpg",
      itemDescription:
      "Handmade pancake serve with fresh berries, lotus biscuits crumb , Maple syrup with whipped cream",
      itemPrice: 2.9,
      itemCalories: 0),
  MenuData(
      itemID: 72,
      itemName: "Oz Berry Protein Waffles",
      itemImage: "assets/img/oz_berry_waffles.jpg",
      itemDescription:
      "Hand made waffle served with fresh berries and pomegranate, lotus biscuits crumb , Raspberry ice cream with strawberry sauce.",
      itemPrice: 3.1,
      itemCalories: 0),
  MenuData(
      itemID: 73,
      itemName: "Oz chocolate Protein Waffles",
      itemImage: "assets/img/oz_chocolate_waffles.jpg",
      itemDescription:
      "Hand made Waffle served with fresh berries and pomegranate, lotus biscuits crumb with vanilla ice cream and chocolate sauce.",
      itemPrice: 3.5,
      itemCalories: 0),
  MenuData(
      itemID: 62,
      itemName: "Oz classic Avocado Toast",
      itemImage: "assets/img/oz_classic_avocado_toast.jpg",
      itemDescription:
      "Toasted Sourdough bread, Guacamole, Poach Eggs , feta cheese, Fresh Pomegranate seeds and Garnish with chili flakes, sesame seeds . Parsley and Sakura mix.",
      itemPrice: 3.1,
      itemCalories: 400),
  MenuData(
      itemID: 63,
      itemName: "Grilled Mushrooms & Spinach Toast",
      itemImage: "assets/img/grilled_mushrooms__spinach_toast.jpg",
      itemDescription:
      "Toasted Sourdough bread, hummus, sauté spinach , Grilled Mushrooms and cherry Tomato , Garnish with chili flakes, sesame seeds, parsley and Sakura mix",
      itemPrice: 3.3,
      itemCalories: 368),
  MenuData(
      itemID: 64,
      itemName: "Labneh Zattar Toast",
      itemImage: "assets/img/labneh_zattar_toast.jpg",
      itemDescription:
      "Toasted sourdough bread, Labneh zattar mixture, Garnish with Sakura mix",
      itemPrice: 2.4,
      itemCalories: 331),
  MenuData(
      itemID: 65,
      itemName: "Guacamole Halloumi Toast",
      itemImage: "assets/img/guacamole_halloumi_toast.jpg",
      itemDescription:
      "Toasted sourdough bread , Sun-dried tomato sliced, grilled halloumi, Garnish with chili flakes , sesame seeds , parsley and Sakura mix .",
      itemPrice: 3.7,
      itemCalories: 501),
  MenuData(
      itemID: 66,
      itemName: "Truffle Mushroom & Egg Toast",
      itemImage: "assets/img/truffle_mushroom__egg_toast.jpg",
      itemDescription: "",
      itemPrice: 3.7,
      itemCalories: 434),
  MenuData(
      itemID: 67,
      itemName: "Olive Tapenade Halloumi Toast",
      itemImage: "assets/img/olive_tapenade_halloumi_toast.jpg",
      itemDescription: "",
      itemPrice: 3.4,
      itemCalories: 534),
  MenuData(
      itemID: 68,
      itemName: "Beetroot Hummus & Avocado Toast with Poached Egg",
      itemImage: "assets/img/beetroot_hummus__avocado_toast_with_egg.jpg",
      itemDescription:
      "Toasted sourdough bread , Beetroot hummus , sliced avocado , poached egg , almond flakes , Garnish with chili flakes , sesame seeds, parsley and Sakura mix",
      itemPrice: 3.7,
      itemCalories: 579),
  MenuData(
      itemID: 69,
      itemName: "Classic Egg Benedict",
      itemImage: "assets/img/classic_egg_benedict.jpg",
      itemDescription:
      "English Muffins buildup with spinach , poached egg, hollandaise sauce garnish with dill and Sakura mix served with wild rocket salad and cherry tomato .",
      itemPrice: 2.8,
      itemCalories: 446),
  MenuData(
      itemID: 70,
      itemName: "Scrambled Egg & Truffle Mushroom Sandwich",
      itemImage: "assets/img/scrambled_egg__truffle_mushroom_sandwich.jpg",
      itemDescription:
      "Brioche bun stuffed with Italian tomato sauce ,,scrambled egg, truffle mushroom, cheddar cheese . Garnish with parsley serve with wild rocket salad cans cherry tomato",
      itemPrice: 2.9,
      itemCalories: 543),
  MenuData(
      itemID: 71,
      itemName: "Oz Berry Pancake",
      itemImage: "assets/img/oz_berry_pancake.jpg",
      itemDescription:
      "Handmade pancake serve with fresh berries, lotus biscuits crumb , Maple syrup with whipped cream",
      itemPrice: 2.9,
      itemCalories: 0),
  MenuData(
      itemID: 72,
      itemName: "Oz Berry Protein Waffles",
      itemImage: "assets/img/oz_berry_waffles.jpg",
      itemDescription:
      "Hand made waffle served with fresh berries and pomegranate, lotus biscuits crumb , Raspberry ice cream with strawberry sauce.",
      itemPrice: 3.1,
      itemCalories: 0),
  MenuData(
      itemID: 73,
      itemName: "Oz chocolate Protein Waffles",
      itemImage: "assets/img/oz_chocolate_waffles.jpg",
      itemDescription:
      "Hand made Waffle served with fresh berries and pomegranate, lotus biscuits crumb with vanilla ice cream and chocolate sauce.",
      itemPrice: 3.5,
      itemCalories: 0),
];
static List<MenuData> bestSeller = [

  MenuData(
      itemID: 63,
      itemName: "Grilled Mushrooms & Spinach Toast",
      itemImage: "assets/img/grilled_mushrooms__spinach_toast.jpg",
      itemDescription:
      "Toasted Sourdough bread, hummus, sauté spinach , Grilled Mushrooms and cherry Tomato , Garnish with chili flakes, sesame seeds, parsley and Sakura mix",
      itemPrice: 3.3,
      itemCalories: 368),
  MenuData(
      itemID: 1,
      itemName: "Espresso",
      itemImage: "assets/img/espresso.jpg",
      itemDescription: "itemDescription",
      itemPrice: 1.5,
      itemCalories: 0),
  MenuData(
      itemID: 34,
      itemName: "Philly Steak Sandwich",
      itemImage: "",
      itemDescription:
      "Beef ,multi seeds brown bread , green pepper , mushroom , white onion , cheese",
      itemPrice: 2.8,
      itemCalories: 470),
  MenuData(
      itemID: 54,
      itemName: "Peanuts Cocnuts Healthy Balls",
      itemImage: "assets/img/peanuts_cocnuts_healthy_balls.jpg",
      itemDescription: "",
      itemPrice: 1.5,
      itemCalories: 210),
];
}

/*
class MenuData {
  final int itemID;
  final int itemCalories;
  final String itemName;
  String itemImage;
  final String itemCategory;
  final String itemDescription;
  final double itemPrice;

  MenuData({
    required this.itemID,
    required this.itemCalories,
    required this.itemName,
    required this.itemImage,
    required this.itemCategory,
    required this.itemDescription,
    required this.itemPrice,
  });
}

List<MenuData> menuItems = [
  MenuData(
      itemID: 1,
      itemName: "Espresso",
      itemImage: "assets/img/espresso.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.5,
      itemCalories: 0),
  MenuData(
      itemID: 2,
      itemName: "Americano",
      itemImage: "assets/img/americano.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.65,
      itemCalories: 0),
  MenuData(
      itemID: 3,
      itemName: "Cortado",
      itemImage: "assets/img/cortado.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 35),
  MenuData(
      itemID: 4,
      itemName: "Flat White",
      itemImage: "assets/img/flat_white.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 80),
  MenuData(
      itemID: 5,
      itemName: "Cappuccino",
      itemImage: "assets/img/cappuccino.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.9,
      itemCalories: 100),
  MenuData(
      itemID: 6,
      itemName: "Latte",
      itemImage: "assets/img/latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 100),
  MenuData(
      itemID: 7,
      itemName: "Spanish Latte",
      itemImage: "assets/img/spanish_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 8,
      itemName: "White Mocha",
      itemImage: "assets/img/white_mocha.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 360),
  MenuData(
      itemID: 9,
      itemName: "Rose Latte",
      itemImage: "assets/img/rose_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 200),
  MenuData(
      itemID: 10,
      itemName: "Dolce de Leche Latte",
      itemImage: "assets/img/dolce_de_leche_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 11,
      itemName: "Matcha Latte",
      itemImage: "assets/img/matcha_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 110),
  MenuData(
      itemID: 12,
      itemName: "Turmeric Latte",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 110),
  MenuData(
      itemID: 13,
      itemName: "V60",
      itemImage: "assets/img/v60.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 14,
      itemName: "Oz Hot Chocolate",
      itemImage: "assets/img/oz_hot_chocolate.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 230),
  MenuData(
      itemID: 15,
      itemName: "Icaed Americano",
      itemImage: "assets/img/iced_americano.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 1.65,
      itemCalories: 0),
  MenuData(
      itemID: 16,
      itemName: "Iced Latte",
      itemImage: "assets/img/iced_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.1,
      itemCalories: 100),
  MenuData(
      itemID: 17,
      itemName: "Iced Spanish Latte",
      itemImage: "assets/img/iced_spanish_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 18,
      itemName: "Iced White Mocha",
      itemImage: "assets/img/iced_white_mocha.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 360),
  MenuData(
      itemID: 19,
      itemName: "Iced Rose Latte",
      itemImage: "assets/img/iced_rose_latte.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.35,
      itemCalories: 200),
  MenuData(
      itemID: 20,
      itemName: "Iced Dolce de Leche Latte",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 260),
  MenuData(
      itemID: 21,
      itemName: "Iced Matcha Latte",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 110),
  MenuData(
      itemID: 22,
      itemName: "Oz Iced Shaken",
      itemImage: "assets/img/oz_iced_shaken.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.4,
      itemCalories: 390),
  MenuData(
      itemID: 23,
      itemName: "Iced Shaken Sugar free Caramel",
      itemImage: "assets/img/iced_shaken_sugar_free_caramel.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.4,
      itemCalories: 130),
  MenuData(
      itemID: 24,
      itemName: "Iced V60",
      itemImage: "assets/img/iced_v60.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 25,
      itemName: "Cold Brew",
      itemImage: "assets/img/cold_brew.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.7,
      itemCalories: 0),
  MenuData(
      itemID: 26,
      itemName: "Classic Mojito Sugar free",
      itemImage: "assets/img/classic_mojito_sugarfree.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 27,
      itemName: "Pinacolada Mojito Sugar free",
      itemImage: "assets/img/pinacolada_mojito_sugarfree.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 28,
      itemName: "Strawberry Mojito",
      itemImage: "assets/img/strawberry_mojito.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.6,
      itemCalories: 25),
  MenuData(
      itemID: 29,
      itemName: "Detox Water",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: .5,
      itemCalories: 0),
  MenuData(
      itemID: 30,
      itemName: "Fresh Juices",
      itemImage: "assets/img/fresh_juices.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.0,
      itemCalories: 90),
  MenuData(
      itemID: 31,
      itemName: "Oz Signature Frappe",
      itemImage: "assets/img/oz_signature_frappe.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 440),
  MenuData(
      itemID: 31,
      itemName: "Caramel Mocha Frappe",
      itemImage: "assets/img/caramel_mocha_frappe.jpg",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 520),
  MenuData(
      itemID: 32,
      itemName: "Spanish Rose Frappe",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "itemDescription",
      itemPrice: 2.5,
      itemCalories: 240),
  MenuData(
      itemID: 33,
      itemName: "Strawberry Matcha",
      itemImage: "",
      itemCategory: "Drinks",
      itemDescription: "Strawberry Sauce, Matcha powder, Milk",
      itemPrice: 2.5,
      itemCalories: 150),
  MenuData(
      itemID: 34,
      itemName: "Philly Steak Sandwich",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription:
          "Beef ,multi seeds brown bread , green pepper , mushroom , white onion , cheese",
      itemPrice: 2.8,
      itemCalories: 470),
  MenuData(
      itemID: 35,
      itemName: "Halloumi Zaatar Sandwich",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription:
          "Grilled Halloumi , zaatar panini bread , Tomato , Cucumber",
      itemPrice: 2.5,
      itemCalories: 470),
  MenuData(
      itemID: 36,
      itemName: "Brisket Sliders",
      itemImage: "assets/img/brisket_sliders.jpg",
      itemCategory: "Meals",
      itemDescription:
          "Beef brisket, potato bun slider, cheese, coleslaw, lettuce",
      itemPrice: 2.9,
      itemCalories: 440),
  MenuData(
      itemID: 37,
      itemName: "Shredded Chicken Sliders",
      itemImage: "assets/img/shredded_chicken_sliders.jpg",
      itemCategory: "Meals",
      itemDescription:
          "Shredded Chicken, potato bun, cheese, coleslaw, lettuce",
      itemPrice: 2.4,
      itemCalories: 390),
  MenuData(
      itemID: 38,
      itemName: "Turkey Omelet Rye Sandwich",
      itemImage: "assets/img/turkey_omelet_rye_sandwich.jpg",
      itemCategory: "Meals",
      itemDescription:
          "Turkey, Egg, Spanish, Rye toast, cheddar cheese, lettuce.",
      itemPrice: 2.3,
      itemCalories: 430),
  MenuData(
      itemID: 39,
      itemName: "Turkey Cheese Sandwich Slices",
      itemImage: "assets/img/turkey_cheese_sandwich_slices.jpg",
      itemCategory: "Meals",
      itemDescription: "",
      itemPrice: 2.3,
      itemCalories: 410),
  MenuData(
      itemID: 40,
      itemName: "Egg and Turkey Croissant",
      itemImage: "assets/img/egg_and_turkey_croissant.jpg",
      itemCategory: "Meals",
      itemDescription: "Egg, Turkey, croissant, cheddar cheese, sause",
      itemPrice: 2.5,
      itemCalories: 500),
  MenuData(
      itemID: 41,
      itemName: "Smoked turkey Croissant",
      itemImage: "assets/img/smoked_turkey_croissant.jpg",
      itemCategory: "Meals",
      itemDescription: "",
      itemPrice: 2.3,
      itemCalories: 0),
  MenuData(
      itemID: 42,
      itemName: "Labneh Zaatar Croissant",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "assets/img/lebna_zaatar_croissant.jpg",
      itemPrice: 1.9,
      itemCalories: 410),
  MenuData(
      itemID: 43,
      itemName: "Halloumi Croissant",
      itemImage: "assets/img/halloumi_croissant.jpg",
      itemCategory: "Meals",
      itemDescription: "Grill Halloumi, croissant, pesto sause",
      itemPrice: 2.4,
      itemCalories: 500),
  MenuData(
      itemID: 44,
      itemName: "Grilled Chicken Sandwich",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription:
          "Grilled chicken breast, Eggplants, Cheese, Brown Panini Bread",
      itemPrice: 2.5,
      itemCalories: 460),
  MenuData(
      itemID: 45,
      itemName: "Chicken Teriyaki",
      itemImage: "assets/img/chicken_teriyaki.jpg",
      itemCategory: "Meals",
      itemDescription:
          "Grill Chicken, white rice, capsicum red, capsicum green, Spring onion, Sesame seed, Sause",
      itemPrice: 2.9,
      itemCalories: 430),
  MenuData(
      itemID: 46,
      itemName: "chicken Biryani",
      itemImage: "assets/img/chicken_biryani.jpg",
      itemCategory: "Meals",
      itemDescription: "",
      itemPrice: 2.7,
      itemCalories: 440),
  MenuData(
      itemID: 47,
      itemName: "Chicken teriyaki linguine noodles",
      itemImage: "assets/img/chicken_teriyaki_noodles.jpg",
      itemCategory: "Meals",
      itemDescription: "",
      itemPrice: 2.7,
      itemCalories: 380),
  MenuData(
      itemID: 48,
      itemName: "Chicken salad",
      itemImage: "assets/img/chicken_salad.jpg",
      itemCategory: "Meals",
      itemDescription: "Mixed greens, Chicken, Balsamic Mustard Dressing",
      itemPrice: 2.3,
      itemCalories: 0),
  MenuData(
      itemID: 49,
      itemName: "Alfredo Pasta",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "Chicken, Pasta, Mushroom, Creamy Sauce",
      itemPrice: 2.8,
      itemCalories: 530),
  MenuData(
      itemID: 50,
      itemName: "Chicken Stroganoff",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "Rice, Creamy Sauce Chicken",
      itemPrice: 2.9,
      itemCalories: 550),
  MenuData(
      itemID: 51,
      itemName: "Thai Coconut Curry",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "Rice, Beef, Coconut Curry, Vegetables",
      itemPrice: 3.4,
      itemCalories: 440),
  MenuData(
      itemID: 52,
      itemName: "Cheese Sandwich",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "Three cheese, with Sun dried Tomato",
      itemPrice: 1.9,
      itemCalories: 320),
  MenuData(
      itemID: 53,
      itemName: "Egg and Cheese Sandwich",
      itemImage: "",
      itemCategory: "Meals",
      itemDescription: "",
      itemPrice: 2.0,
      itemCalories: 0),
  MenuData(
      itemID: 54,
      itemName: "Peanuts Cocnuts Healthy Balls",
      itemImage: "assets/img/peanuts_cocnuts_healthy_balls.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 1.5,
      itemCalories: 210),
  MenuData(
      itemID: 55,
      itemName: "Açaí bowl",
      itemImage: "assets/img/açaí_bowl.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 3.9,
      itemCalories: 0),
  MenuData(
      itemID: 56,
      itemName: "French toast",
      itemImage: "assets/img/french_toast.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 2.8,
      itemCalories: 0),
  MenuData(
      itemID: 57,
      itemName: "Pecan pie",
      itemImage: "assets/img/pecan_pie.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 2.5,
      itemCalories: 0),
  MenuData(
      itemID: 58,
      itemName: "Chocolate cookies",
      itemImage: "assets/img/chocolate_cookies.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 1.4,
      itemCalories: 0),
  MenuData(
      itemID: 59,
      itemName: "Lemon cake",
      itemImage: "assets/img/lemon_cake.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 1.25,
      itemCalories: 0),
  MenuData(
      itemID: 60,
      itemName: "Nutella pancake",
      itemImage: "assets/img/nutella_pancake.jpg",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 3.1,
      itemCalories: 0),
  MenuData(
      itemID: 61,
      itemName: "Granula Greek Yughort",
      itemImage: "",
      itemCategory: "Desserts",
      itemDescription: "",
      itemPrice: 1.8,
      itemCalories: 0),
  MenuData(
      itemID: 62,
      itemName: "Oz classic Avocado Toast",
      itemImage: "assets/img/oz_classic_avocado_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Toasted Sourdough bread, Guacamole, Poach Eggs , feta cheese, Fresh Pomegranate seeds and Garnish with chili flakes, sesame seeds . Parsley and Sakura mix.",
      itemPrice: 3.1,
      itemCalories: 400),
  MenuData(
      itemID: 63,
      itemName: "Grilled Mushrooms & Spinach Toast",
      itemImage: "assets/img/grilled_mushrooms__spinach_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Toasted Sourdough bread, hummus, sauté spinach , Grilled Mushrooms and cherry Tomato , Garnish with chili flakes, sesame seeds, parsley and Sakura mix",
      itemPrice: 3.3,
      itemCalories: 368),
  MenuData(
      itemID: 64,
      itemName: "Labneh Zattar Toast",
      itemImage: "assets/img/labneh_zattar_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Toasted sourdough bread, Labneh zattar mixture, Garnish with Sakura mix",
      itemPrice: 2.4,
      itemCalories: 331),
  MenuData(
      itemID: 65,
      itemName: "Guacamole Halloumi Toast",
      itemImage: "assets/img/guacamole_halloumi_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Toasted sourdough bread , Sun-dried tomato sliced, grilled halloumi, Garnish with chili flakes , sesame seeds , parsley and Sakura mix .",
      itemPrice: 3.7,
      itemCalories: 501),
  MenuData(
      itemID: 66,
      itemName: "Truffle Mushroom & Egg Toast",
      itemImage: "assets/img/truffle_mushroom__egg_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription: "",
      itemPrice: 3.7,
      itemCalories: 434),
  MenuData(
      itemID: 67,
      itemName: "Olive Tapenade Halloumi Toast",
      itemImage: "assets/img/olive_tapenade_halloumi_toast.jpg",
      itemCategory: "Breakfast",
      itemDescription: "",
      itemPrice: 3.4,
      itemCalories: 534),
  MenuData(
      itemID: 68,
      itemName: "Beetroot Hummus & Avocado Toast with Poached Egg",
      itemImage: "assets/img/beetroot_hummus__avocado_toast_with_egg.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Toasted sourdough bread , Beetroot hummus , sliced avocado , poached egg , almond flakes , Garnish with chili flakes , sesame seeds, parsley and Sakura mix",
      itemPrice: 3.7,
      itemCalories: 579),
  MenuData(
      itemID: 69,
      itemName: "Classic Egg Benedict",
      itemImage: "assets/img/classic_egg_benedict.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "English Muffins buildup with spinach , poached egg, hollandaise sauce garnish with dill and Sakura mix served with wild rocket salad and cherry tomato .",
      itemPrice: 2.8,
      itemCalories: 446),
  MenuData(
      itemID: 70,
      itemName: "Scrambled Egg & Truffle Mushroom Sandwich",
      itemImage: "assets/img/scrambled_egg__truffle_mushroom_sandwich.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Brioche bun stuffed with Italian tomato sauce ,,scrambled egg, truffle mushroom, cheddar cheese . Garnish with parsley serve with wild rocket salad cans cherry tomato",
      itemPrice: 2.9,
      itemCalories: 543),
  MenuData(
      itemID: 71,
      itemName: "Oz Berry Pancake",
      itemImage: "assets/img/oz_berry_pancake.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Handmade pancake serve with fresh berries, lotus biscuits crumb , Maple syrup with whipped cream",
      itemPrice: 2.9,
      itemCalories: 0),
  MenuData(
      itemID: 72,
      itemName: "Oz Berry Protein Waffles",
      itemImage: "assets/img/oz_berry_waffles.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Hand made waffle served with fresh berries and pomegranate, lotus biscuits crumb , Raspberry ice cream with strawberry sauce.",
      itemPrice: 3.1,
      itemCalories: 0),
  MenuData(
      itemID: 73,
      itemName: "Oz chocolate Protein Waffles",
      itemImage: "assets/img/oz_chocolate_waffles.jpg",
      itemCategory: "Breakfast",
      itemDescription:
          "Hand made Waffle served with fresh berries and pomegranate, lotus biscuits crumb with vanilla ice cream and chocolate sauce.",
      itemPrice: 3.5,
      itemCalories: 0),
];
*/
